# 应用服务 WEB 访问端口
server:
    port: 8080
# 应用名称
spring:
    application:
        name: demo
    shardingsphere:
        datasource:
            names: master,slave0,slave1
            master:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/taobao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: 123456
            slave0:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/taobao_r1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: 123456
            slave1:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/taobao_r2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: 123456
        masterslave:
            load-balance-algorithm-type: round_robin
            name: ms
            slave-data-source-names: slave0,slave1
            master-data-source-name: master
        props:
            sql:
                show: true


mybatis:
    check-config-location: true
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mapper/*Dao.xml

