# 应用服务 WEB 访问端口
server:
    port: 8080
# 应用名称
spring:
    application:
        name: demo
    datasource:
        write:
            url: jdbc:mysql://localhost:3306/taobao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
            username: root
            password: 123456
        read1:
            url: jdbc:mysql://localhost:3306/taobao_r1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
            username: root
            password: 123456
        read2:
            url: jdbc:mysql://localhost:3306/taobao_r2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
            username: root
            password: 123456

mybatis:
    check-config-location: true
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mapper/*Dao.xml
